<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class YemenCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $langArId = 1;
        $langEnId = 2;

        // Insert Saudi Arabia Country
        $countryId = DB::table('countries')->insertGetId([
            'code' => 'YE',
            'flag' => 'ye.svg',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Insert Country Translations
        DB::table('country_translations')->insert([
            ['country_id' => $countryId, 'language_id' => $langArId, 'name' => 'اليمن'],
            ['country_id' => $countryId, 'language_id' => $langEnId, 'name' => 'Yemen'],
        ]);

        // Regions and their respective cities
        $regions = [
            "Adan Governorate" => [
                "ar" => "محافظة عدن",
                "cities" => [
                    "Aden" => "عدن",
                    "Al Buraiqeh" => "البريقة",
                    "Al Mansura" => "المنصورة",
                    "Al Mualla" => "المعلا",
                    "Ash Shaikh Outhman" => "الشيخ عثمان",
                    "Attawahi" => "التواهي",
                    "Craiter" => "كريتر",
                    "Dar Sad" => "دار سعد",
                ],
            ],
            "Amran Governorate" => [
                "ar" => "محافظة عمران",
                "cities" => [
                    "‘Amrān" => "عمران",
                    "Al Ashah" => "الأشاعه",
                    "Al Madan" => "المدان",
                    "Al Qaflah" => "القفلة",
                    "As Sawd" => "السود",
                    "As Sudah" => "السوده",
                    "Bani Suraim" => "بني صريم",
                    "Dhi Bin" => "ذيبين",
                    "Habur Zulaymah" => "حبور ظليمة",
                    "Harf Sufyan" => "حرف سفيان",
                    "Hooth" => "حوث",
                    "Iyal Surayh" => "عيال سريح",
                    "Jabal Iyal Yazid" => "جبل عيال يزيد",
                    "Khamir" => "خمر",
                    "Kharif" => "خارف",
                    "Maswar" => "مسور",
                    "Raydah" => "ريدة",
                    "Shahārah" => "شهارة",
                    "Suwayr" => "سوير",
                    "Thula" => "ثُلاء",
                ],
            ],
            "Abyan Governorate" => [
                "ar" => "محافظة أبين",
                "cities" => [
                    "Ahwar" => "أحور",
                    "Aḩwar" => "أحور",
                    "Al Mahfad" => "المحفد",
                    "Al Wade'a" => "الوضيع",
                    "Jawf al Maqbābah" => "جوف المقبابة",
                    "Jayshan" => "جيشان",
                    "Khanfir" => "خنفر",
                    "Lawdar" => "لودر",
                    "Mudiyah" => "مودية",
                    "Mūdīyah" => "مودية",
                    "Rasad" => "رصد",
                    "Sarar" => "سرار",
                    "Sibah" => "سيبان",
                    "Zingibar" => "زنجبار",
                    "Zinjibār" => "زنجبار",
                ],
            ],
            "Al Bayda' Governorate" => [
                "ar" => "محافظة البيضاء",
                "cities" => [
                    "Al A'rsh" => "العَرش",
                    "Al Bayda" => "البيضاء",
                    "Al Bayda City" => "مدينة البيضاء",
                    "Al Bayḑā’" => "البيضاء",
                    "Al Malagim" => "الملاجم",
                    "Al Quraishyah" => "القريشية",
                    "Ar Ryashyyah" => "الرياشية",
                    "As Sawadiyah" => "السوادية",
                    "As Sawma'ah" => "الصومعة",
                    "Ash Sharafayn" => "الشرفين",
                    "At Taffah" => "الطفة",
                    "Az Zahir" => "الظاهر",
                    "Dhi Na'im" => "ذي ناعم",
                    "Maswarah" => "مسورة",
                    "Mukayras" => "مكيراس",
                    "Na'man" => "نعمان",
                    "Nati'" => "ناطع",
                    "Radā‘" => "رداع",
                    "Radman Al Awad" => "ردمان العواذل",
                    "Sabah" => "صباح",
                    "Wald Rabi'" => "ولد ربيع",
                ],
            ],
            "Al Hudaydah Governorate" => [
                "ar" => "محافظة الحديدة",
                "cities" => [
                    "Ad Dahi" => "الدُّحي",
                    "Ad Durayhimi" => "الدريهمي",
                    "Al Garrahi" => "القرّاحي",
                    "Al Hajjaylah" => "الحجيلة",
                    "Al Hali" => "الحالي",
                    "Al Hawak" => "الحوك",
                    "Al Ḩudaydah" => "الحديدة",
                    "Al Mansuriyah" => "المنصورية",
                    "Al Marawi'ah" => "المراوعة",
                    "Al Mighlaf" => "المِغلاف",
                    "Al Mina" => "الميناء",
                    "Al Munirah" => "المنيرة",
                    "Al Qanawis" => "القناوص",
                    "Alluheyah" => "اللحية",
                    "As Salif" => "الصليف",
                    "Aş Şalīf" => "الصليف",
                    "As Sukhnah" => "السخنة",
                    "At Tuhayat" => "التحيتا",
                    "Az Zaydīyah" => "الزيدية",
                    "Az Zuhrah" => "الزهرة",
                    "Bājil" => "باجل",
                    "Bayt al Faqīh" => "بيت الفقيه",
                    "Bura" => "بُرَع",
                    "Hays" => "حيس",
                    "Jabal Ra's" => "جبل راس",
                    "Kamaran" => "كمران",
                    "Zabīd" => "زبيد",
                ],
            ],
            "Al Jawf Governorate" => [
                "ar" => "محافظة الجوف",
                "cities" => [
                    "Al ‘Inān" => "العنان",
                    "Al Ghayl" => "الغيل",
                    "Al Hazm" => "الحزم",
                    "Al Ḩazm" => "الحزم",
                    "Al Humaydat" => "الحُميدات",
                    "Al Khalq" => "الخلق",
                    "Al Maslub" => "المصلوب",
                    "Al Matammah" => "المطمة",
                    "Al Maton" => "المتون",
                    "Az Zahir" => "الظاهر",
                    "Barţ al ‘Anān" => "برط العنان",
                    "Khabb wa ash Sha'af" => "خب والشعف",
                    "Kharab Al Marashi" => "خراب المراشي",
                    "Rajuzah" => "رجوزة",
                ],
            ],
            "Al Mahrah Governorate" => [
                "ar" => "محافظة المهرة",
                "cities" => [
                    "Al Ghaydah" => "الغَيْضة",
                    "Al Ghayz̧ah" => "الغَيْضة",
                    "Al Masilah" => "المَسيلة",
                    "Hat" => "حات",
                    "Hawf" => "حوف",
                    "Huswain" => "حصوين",
                    "Man'ar" => "منعر",
                    "Qishn" => "قشن",
                    "Sayhut" => "سيحوت",
                    "Shahan" => "شحن",
                ],
            ],
            "Al Mahwit Governorate" => [
                "ar" => "محافظة المحويت",
                "cities" => [
                    "Al Khabt" => "الخبت",
                    "Al Mahwait" => "المحويت",
                    "Al Maḩwīt" => "المحويت",
                    "Ar Rujum" => "الرجم",
                    "Aţ Ţawīlah" => "الطويلة",
                    "Bani Sa'd" => "بني سعد",
                    "Hufash" => "حفاش",
                    "Milhan" => "ملحان",
                    "Shibām Kawkabān" => "شبام كوكبان",
                ],
            ],
            "Dhamar Governorate" => [
                "ar" => "محافظة ذمار",
                "cities" => [
                    "‘Ans" => "عنس",
                    "Al Hada" => "الحداء",
                    "Al Manar" => "المنار",
                    "Al-Medy Village" => "قرية المدّي",
                    "Dawran Aness" => "دُوران عنس",
                    "Dhamār" => "ذمار",
                    "Jabal Ash sharq" => "جبل الشرق",
                    "Jahran" => "جهران",
                    "Maghirib Ans" => "مغرب عنس",
                    "Mayfa'at Anss" => "ميفعة عنس",
                    "Utmah" => "عُتمة",
                    "Wusab Al Ali" => "وصاب العالي",
                    "Wusab As Safil" => "وصاب السافل",
                ],
            ],
            "Hadhramaut Governorate" => [
                "ar" => "محافظة حضرموت",
                "cities" => [
                    "Ad Dis" => "الديس",
                    "Ad Dīs ash Sharqīyah" => "الديس الشرقية",
                    "Adh Dhlia'ah" => "الضليعة",
                    "Al Abr" => "العبر",
                    "Al Ḩamdī" => "الحمدي",
                    "Al Mukalla" => "المكلا",
                    "Al Mukalla City" => "مدينة المكلا",
                    "Al Qaf" => "القف",
                    "Al Qatn" => "القطن",
                    "Amd" => "عمد",
                    "Ar Raydah Wa Qusayar" => "الريدة وقصيعر",
                    "As Sawm" => "الصوم",
                    "Ash Shihr" => "الشحر",
                    "Ash Shiḩr" => "الشحر",
                    "At Taḩāluf" => "التحالف",
                    "Brom Mayfa" => "بروم ميفع",
                    "Daw'an" => "دوعن",
                    "Ghayl Ba Wazir" => "غيل باوزير",
                    "Ghayl Bin Yamin" => "غيل بن يمين",
                    "Hagr As Sai'ar" => "حجر السعيد",
                    "Hajr" => "حجر",
                    "Huraidhah" => "حريضة",
                    "Kilmia" => "كليمة",
                    "Mukalla" => "المكلا",
                    "Rakhyah" => "رخية",
                    "Rumah" => "رُماه",
                    "Sah" => "ساه",
                    "Sayun" => "سيئون",
                    "Shibam" => "شبام",
                    "Suḩayl Shibām" => "سهيل شبام",
                    "Tarim" => "تريم",
                    "Tarīm" => "تريم",
                    "Thamud" => "ثمود",
                    "Wadi Al Ayn" => "وادي العين",
                    "Yabuth" => "يابوث",
                    "Zamakh wa Manwakh" => "زمخ ومنوخ",
                ],
            ],
            "Hajjah Governorate" => [
                "ar" => "محافظة حجة",
                "cities" => [
                    "Abs" => "عبس",
                    "Aflah Al Yaman" => "أفلح اليمن",
                    "Aflah Ash Shawm" => "أفلح الشام",
                    "Al Jamimah" => "الجميمة",
                    "Al Maghrabah" => "المغربة",
                    "Al Mahabishah" => "المحابشة",
                    "Al Miftah" => "المفتاح",
                    "Ash Shaghadirah" => "الشغادرة",
                    "Ash Shahil" => "الشاهل",
                    "Aslem" => "أسلم",
                    "Bakil Al Mir" => "بكيل المير",
                    "Banī al ‘Awwām" => "بني العوام",
                    "Bani Al Awam" => "بني العوام",
                    "Bani Qa'is" => "بني قيس",
                    "Hajjah" => "حجة",
                    "Ḩajjah" => "حجة",
                    "Harad District" => "مديرية حرض",
                    "Hayran" => "حيران",
                    "Khayran Al Muharraq" => "خيران المحرق",
                    "Ku'aydinah" => "كعيدنة",
                    "Kuhlan Affar" => "كحلان عفار",
                    "Kuhlan Ash Sharaf" => "كحلان الشرف",
                    "Kushar" => "كشر",
                    "Mabyan" => "مبين",
                    "Midi" => "ميدي",
                    "Mustaba" => "مستباء",
                    "Najrah" => "نجرة",
                    "Qafl Shamer" => "قفل شمر",
                    "Qarah" => "قارة",
                    "Sharas" => "شرس",
                    "Wadhrah" => "وضرة",
                    "Washḩah" => "وشحة",
                ],
            ],
            "Ibb Governorate" => [
                "ar" => "محافظة إب",
                "cities" => [
                    "Al ‘Udayn" => "العدين",
                    "Al Dhihar" => "الظهار",
                    "Al Makhādir" => "المخادر",
                    "Al Mashannah" => "المشنة",
                    "Al Qafr" => "القفر",
                    "An Nādirah" => "النادرة",
                    "Ar Radmah" => "الرَضمة",
                    "As Sabrah" => "السبرة",
                    "As Saddah" => "السدة",
                    "As Sayyani" => "السياني",
                    "Ash Sha'ir" => "الشعاير",
                    "Ba'dan" => "بعدان",
                    "Dhī as Sufāl" => "ذي السفال",
                    "Far Al Udayn" => "فرع العدين",
                    "Hazm Al Udayn" => "حزم العدين",
                    "Hubaysh" => "حبيش",
                    "Ibb" => "إب",
                    "Jiblah" => "جبلة",
                    "Mudhaykhirah" => "مذيخرة",
                    "Yarīm" => "يريم",
                ],
            ],
            "Lahij Governorate" => [
                "ar" => "محافظة لحج",
                "cities" => [
                    "Al Hawtah" => "الحوطة",
                    "Al Ḩabīlayn" => "الحبيلين",
                    "Al Had" => "الحد",
                    "Al Madaribah Wa Al Arah" => "المضاربة والعارة",
                    "Al Maflahy" => "المفلحي",
                    "Al Maqatirah" => "المقاطرة",
                    "Al Milah" => "الملاح",
                    "Al Musaymir" => "المسيمير",
                    "Al Musaymīr" => "المسيمير",
                    "Al Qabbaytah" => "القبيطة",
                    "Habil Jabr" => "حبيل جبر",
                    "Halimayn" => "الحالمين",
                    "Laḩij" => "لحج",
                    "Radfan" => "ردفان",
                    "Tuban" => "تبن",
                    "Tur Al Bahah" => "طور الباحة",
                    "Yafa'a" => "يافع",
                    "Yahr" => "يهر",
                ],
            ],
            "Ma'rib Governorate" => [
                "ar" => "محافظة مأرب",
                "cities" => [
                    "Al Abdiyah" => "العبدية",
                    "Al Jubah" => "الجوبة",
                    "Bidbadah" => "بدبدة",
                    "Ḩarīb" => "حريب",
                    "Harib Al Qaramish" => "حريب القرامش",
                    "Jabal Murad" => "جبل مراد",
                    "Ma'rib" => "مأرب",
                    "Mahliyah" => "ماهلية",
                    "Majzar" => "مجزر",
                    "Marib" => "مأرب",
                    "Marib City" => "مدينة مأرب",
                    "Medghal" => "مدغل",
                    "Raghwan" => "رغوان",
                    "Rahabah" => "رحبة",
                    "Sirwah" => "صرواح",
                ],
            ],
            "Raymah Governorate" => [
                "ar" => "محافظة ريمة",
                "cities" => [
                    "Al Jabin" => "الجبين",
                    "Al Jafariyah" => "الجعفرية",
                    "As Salafiyah" => "السلفية",
                    "Bilad At Ta'am" => "بلاد الطعام",
                    "Kusmah" => "كسمة",
                    "Mazhar" => "مزهر",
                ],
            ],
            "Saada Governorate" => [
                "ar" => "محافظة صعدة",
                "cities" => [
                    "Al Dhaher" => "الظاهر",
                    "Al Hashwah" => "الحشوة",
                    "As Safra" => "الصفراء",
                    "Ash Shawātī" => "الشواطئ",
                    "Baqim" => "باقم",
                    "Ghamr" => "غمر",
                    "Haydan" => "حيدان",
                    "Kitaf wa Al Boqe'e" => "كتاف والبقع",
                    "Majz" => "مجز",
                    "Monabbih" => "منبه",
                    "Qatabir" => "قطابر",
                    "Rāziḩ" => "رازح",
                    "Sa'dah" => "صعدة",
                    "Şa‘dah" => "صعدة",
                    "Saḩār" => "سحار",
                    "Saqayn" => "ساقين",
                    "Sāqayn" => "ساقين",
                    "Shada'a" => "شداء",
                ],
            ],
            "Sana'a Governorate" => [
                "ar" => "محافظة صنعاء",
                "cities" => [
                    "Al Haymah Ad Dakhiliyah" => "الحيمة الداخلية",
                    "Al Haymah Al Kharijiyah" => "الحيمة الخارجية",
                    "Al Husn" => "الحصن",
                    "Al Khāniq" => "الخانق",
                    "Arhab" => "أرحب",
                    "Attyal" => "بني مطر",
                    "Bani Dhabyan" => "بني ضبيان",
                    "Bani Hushaysh" => "بني حشيش",
                    "Bani Matar" => "بني مطر",
                    "Bilad Ar Rus" => "بلاد الروس",
                    "Hamdān" => "همدان",
                    "Jihanah" => "جحانة",
                    "Khwlan" => "خولان",
                    "Manakhah" => "مناخة",
                    "Manākhah" => "مناخة",
                    "Nihm" => "نهم",
                    "Sa'fan" => "صعفان",
                    "Saḩar" => "سحر",
                    "Sanaa" => "صنعاء",
                    "Sanhan" => "سنحان",
                    "Sayyān" => "سيان",
                ],
            ],
            "Shabwah Governorate" => [
                "ar" => "محافظة شبوة",
                "cities" => [
                    "Ain" => "عين",
                    "Al ‘Āqir" => "العاقر",
                    "Al Talh" => "الطلح",
                    "AL-khashā upper" => "الكشا العليا",
                    "Ar Rawdah" => "الروضة",
                    "Arma" => "عرما",
                    "As Said" => "الصعيد",
                    "Ataq" => "عتق",
                    "Bayhan" => "بيحان",
                    "Dhar" => "دهر",
                    "Habban" => "حبّان",
                    "Hatib" => "حطيب",
                    "Jardan" => "جردان",
                    "Khimār" => "خمر",
                    "Mayfa'a" => "ميفعة",
                    "Merkhah Al Ulya" => "مرخة العليا",
                    "Merkhah As Sufla" => "مرخة السفلى",
                    "Nisab" => "نصاب",
                    "Rudum" => "رضوم",
                    "Usaylan" => "عسيلان",
                ],
            ],
            "Socotra Governorate" => [
                "ar" => "محافظة سقطرى",
                "cities" => [
                    "Hadibu" => "حديبو",
                    "Hidaybu" => "حديبو",
                    "Qalansīyah" => "قلنسية",
                    "Qulensya Wa Abd Al Kuri" => "قلنسية وعبد الكوري",
                ],
            ],
            "Ta'izz Governorate" => [
                "ar" => "محافظة تعز",
                "cities" => [
                    "Al Ma'afer" => "المعافر",
                    "Al Mawasit" => "المواسط",
                    "Al Misrakh" => "المصراخ",
                    "Al Mudhaffar" => "المظفر",
                    "Al Mukhā’" => "المخا",
                    "Al Qahirah" => "القاهرة",
                    "Al Wazi'iyah" => "الوازعية",
                    "As Silw" => "الصلو",
                    "Ash Shamayatayn" => "الشمايتين",
                    "At Ta‘izzīyah" => "التعزية",
                    "Dhubab" => "ذوباب",
                    "Dimnat Khadir" => "دمنة خدير",
                    "Hayfan" => "حيفان",
                    "Jabal Habashy" => "جبل حبشي",
                    "Maqbanah" => "مقبنة",
                    "Mashra'a Wa Hadnan" => "مشرعة وحدنان",
                    "Māwīyah" => "ماوية",
                    "Mawza" => "موزع",
                    "Sabir Al Mawadim" => "صبر الموادم",
                    "Salh" => "صالح",
                    "Sama" => "سامع",
                    "Shara'b Ar Rawnah" => "شرعب الرونة",
                    "Shara'b As Salam" => "شرعب السلام",
                    "Ta‘izz" => "تعز",
                    "Village of ALAMRAH" => "قرية العمرة",
                ],
            ],
        ];

        // Insert regions and their translations
        foreach ($regions as $region_en => $region_data) {
            $regionId = DB::table('regions')->insertGetId([
                'country_id' => $countryId,
            ]);

            DB::table('region_translations')->insert([
                ['region_id' => $regionId, 'language_id' => $langArId, 'name' => $region_data['ar']],
                ['region_id' => $regionId, 'language_id' => $langEnId, 'name' => $region_en],
            ]);

            // Insert cities and their translations
            foreach ($region_data['cities'] as $city_en => $city_ar) {
                $cityId = DB::table('cities')->insertGetId([
                    'region_id' => $regionId,
                ]);

                DB::table('city_translations')->insert([
                    ['city_id' => $cityId, 'language_id' => $langArId, 'name' => $city_ar],
                    ['city_id' => $cityId, 'language_id' => $langEnId, 'name' => $city_en],
                ]);
            }
        }
    }
}
